name: First Apps

on:
  push:
    branches:
      - main

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create file
        run: |
          echo "++++ list files ++++" 
          ls -l
          echo "my first github project" > file.txt
          cat file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: file.txt
          path: .

  download-and-display:
    runs-on: ubuntu-latest
    needs: create-and-upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: file.txt

      - name: Display structure of downloaded files
        run: ls -l

      - name: Show contents of file
        run: cat file.txt
