name: First Apps

on:
  push:
    branches:
      - main

jobs:
  create-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create file
        run: |
          echo "++++ list files ++++" 
          
          echo "my first github project" > file.txt 
          ls -l
          cat file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: My-file.txt
          path: ./file.txt

  download-and-display:
    needs: create-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: My-file.txt

      - name: Display structure of downloaded files
        run: |
          ls -l
          cat file.txt
          rm file.txt
                ls -l || true 
      
  run-java:
    needs: download-and-display
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optional
      - name: Build with Maven
        run: mvn -B package --file pom.xml
